[theme]
# Primary accent color for interactive elements.
primaryColor = "#D56868"

# Background color for the main content area.
backgroundColor = "#262626"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#757575"

# Color used for almost all text
textColor = "#f5f5f5"